version: "3.8"

services:
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network

    back:
        build:
            context: ../backend/
        volumes:
            - ../backend/:/app
            - ../backend/target:/app/target
        ports:
            - "8080:8080"
        env_file:
            - .env
        depends_on:
            - postgres
        networks:
            - app_network
    
    front:
        build:
            context: ../frontend/
        volumes:
            - ../frontend/:/app
            - node_modules:/app/node_modules
        ports:
            - "80:4200"
        networks:
            - app_network

    elasticsearch:
        image: elasticsearch:7.9.1
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - test_data:/usr/share/elasticsearch/data/
            - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - discovery.type=single-node
            - http.host=0.0.0.0
            - transport.host=0.0.0.0
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - cluster.name=elasticsearch
            - bootstrap.memory_lock=true
        networks:
            - app_network

    logstash:
        image: logstash:7.9.1
        ports:
            - "5044:5044"
            - "9600:9600"
        volumes:
            - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ls_data:/usr/share/logstash/data
        networks:
            - app_network
        depends_on:
            - elasticsearch

    kibana:
        image: kibana:7.9.1
        ports:
            - "5601:5601"
        volumes:
            - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
            - kb_data:/usr/share/kibana/data
        networks:
            - app_network
        depends_on:
            - elasticsearch

networks:
    app_network:
        driver: bridge

volumes:
    postgres_data:
    node_modules:
    test_data:
    ls_data:
    kb_data:
