name: Flutter

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - run: flutter --version
      - name: Doctor
        run: flutter doctor
        
      - name: analyse
        run: flutter analyze

      - name: Build web
        run: |
          flutter pub get
          flutter build web

      - name: Build APK
        run: flutter build apk